"""Sphinx configuration for the XINIM project.

This configuration connects the Breathe extension so that XML generated by
Doxygen feeds directly into the Sphinx build.  It also summarizes how to
build the documentation for maintainers.

Build steps from the repository root::

    doxygen Doxyfile
    sphinx-build -b html docs/sphinx docs/sphinx/html
"""

from pathlib import Path

# Project metadata displayed in the documentation.
project = "XINIM"  # Name of the project
# Developers credited in the documentation. This edition is curated by
# The 2025 XINIM team with deep gratitude and thanks to Andrew Tanenbaum
# for the foundational concepts that shape XINIM's architecture.
author = "The 2025 XINIM team with deep gratitude and thanks to Andrew Tanenbaum"
version = "0.1"  # Short version string
release = "0.1.0"  # Full version string including patch level

# Extensions that add additional functionality to Sphinx.
extensions = [
    "breathe",  # Integrates Doxygen XML output for API reference
]

# Mapping of projects for the Breathe extension.
breathe_projects = {
    "XINIM": str(Path("..") / "doxygen" / "xml"),
}
breathe_default_project = "XINIM"  # Activate this project by default

# Look and feel configuration for HTML output.
html_theme = "sphinx_rtd_theme"  # Use Read the Docs theme
html_static_path = ["_static"]  # Directory for custom static files
