# Pre-commit configuration for XINIM
# Delegates style and static-analysis checks to wrapper scripts under tools/
# ensuring consistent project-wide formatting and diagnostics.

repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: tools/pre-commit-clang-format.sh
        language: system
        files: '\.(c|cc|cpp|cxx|h|hh|hpp)$'
        pass_filenames: false
      - id: clang-tidy
        name: clang-tidy
        entry: tools/run_clang_tidy.sh
        language: system
        files: '\.(c|cc|cpp|cxx|h|hh|hpp)$'
        pass_filenames: false
      - id: cppcheck
        name: cppcheck
        entry: tools/run_cppcheck.sh
        language: system
        files: '\.(c|cc|cpp|cxx|h|hh|hpp)$'
        pass_filenames: false