/*
 * XINIM System Call Numbers for i386
 *
 * This replaces the stock Linux i386 syscall table inside the vendored
 * dietlibc tree with the XINIM user ABI used by the i486 kernel lane.
 */

/* Debug and timebase */
#define __NR_debug_write                         1
#define __NR_monotonic_ns                        2

/* File I/O */
#define __NR_open                                3
#define __NR_close                               4
#define __NR_read                                5
#define __NR_write                               6
#define __NR_lseek                               7
#define __NR_stat                                8
#define __NR_fstat                               9
#define __NR_access                             10
#define __NR_dup                                11
#define __NR_dup2                               12
#define __NR_pipe                               13
#define __NR_ioctl                              14
#define __NR_fcntl                              15

/* Directory operations */
#define __NR_mkdir                              16
#define __NR_rmdir                              17
#define __NR_chdir                              18
#define __NR_getcwd                             19
#define __NR_link                               20
#define __NR_unlink                             21
#define __NR_rename                             22
#define __NR_chmod                              23
#define __NR_chown                              24
#define __NR_creat                              -1
#define __NR_mknod                              -1
#define __NR_lchown                             -1
#define __NR_mount                              -1
#define __NR_umount                             -1

/* Process management */
#define __NR_exit                               25
#define __NR_fork                               26
#define __NR_execve                             27
#define __NR_wait4                              28
#define __NR_getpid                             29
#define __NR_getppid                            30
#define __NR_kill                               31
#define __NR_signal                             32
#define __NR_rt_sigaction                       33
#define __NR_alarm                              52
#define __NR_getrlimit                          53
#define __NR_setrlimit                          54
#define __NR_getrusage                          55
#define __NR_setsid                             56
#define __NR_umask                              57
#define __NR_nice                               58
#define __NR_setreuid                           59
#define __NR_setregid                           60
#define __NR_rt_sigprocmask                     61
#define __NR_getpgid                            62
#define __NR_getdents                           63
#define __NR_mremap                             64
#define __NR_ptrace                             -1
#define __NR_pause                              -1
#define __NR_times                              -1
#define __NR_acct                               -1
#define __NR_umount2                            -1
#define __NR_lock                               -1

/* Memory management */
#define __NR_brk                                34
#define __NR_mmap                               35
#define __NR_munmap                             36
#define __NR_mprotect                           37

/* IPC */
#define __NR_lattice_connect                    38
#define __NR_lattice_send                       39
#define __NR_lattice_recv                       40
#define __NR_lattice_close                      41

/* Time */
#define __NR_time                               42
#define __NR_gettimeofday                       43
#define __NR_clock_gettime                      44
#define __NR_nanosleep                          45
#define __NR_utime                              -1
#define __NR_sync                               -1

/* User/group IDs */
#define __NR_getuid                             46
#define __NR_geteuid                            47
#define __NR_getgid                             48
#define __NR_getegid                            49
#define __NR_setuid                             50
#define __NR_setgid                             51
#define __NR_fchmod                             72

/* Legacy i386 aliases expected by dietlibc */
#define __NR_waitpid                            __NR_wait4
#define __NR_break                              __NR_brk
#define __NR_sigaction                          __NR_rt_sigaction
#define __NR_sigpending                         -1
#define __NR_sigprocmask                        -1
#define __NR_sigreturn                          -1
#define __NR_sigsuspend                         -1
#define __NR_sgetmask                           -1
#define __NR_ssetmask                           -1
#define __NR_oldstat                            __NR_stat
#define __NR_oldfstat                           __NR_fstat
#define __NR_oldlstat                           -1
#define __NR_oldolduname                        -1
#define __NR_olduname                           -1
#define __NR_stime                              -1
#define __NR_stty                               -1
#define __NR_gtty                               -1
#define __NR_ftime                              -1
#define __NR_prof                               -1
#define __NR_profil                             -1
#define __NR_mpx                                -1
#define __NR_setpgid                            65
#define __NR_ulimit                             -1
#define __NR_chroot                             -1
#define __NR_ustat                              -1
#define __NR_getpgrp                            66
#define __NR_sethostname                        -1
#define __NR_settimeofday                       -1
#define __NR_getgroups                          -1
#define __NR_setgroups                          -1
#define __NR_select                             78
#define __NR_symlink                            69
#define __NR_readlink                           70
#define __NR_uselib                             -1
#define __NR_swapon                             -1
#define __NR_reboot                             -1
#define __NR_readdir                            -1
#define __NR_truncate                           74
#define __NR_ftruncate                          75
#define __NR_fchown                             73
#define __NR_getpriority                        -1
#define __NR_setpriority                        -1
#define __NR_statfs                             107
#define __NR_fstatfs                            -1
#define __NR_ioperm                             -1
#define __NR_socketcall                         -1
#define __NR_syslog                             -1
#define __NR_setitimer                          -1
#define __NR_getitimer                          -1
#define __NR_lstat                              108
#define __NR_iopl                               -1
#define __NR_vhangup                            -1
#define __NR_idle                               -1
#define __NR_vm86old                            -1
#define __NR_swapoff                            -1
#define __NR_sysinfo                            -1
#define __NR_ipc                                -1
#define __NR_fsync                              102
#define __NR_clone                              -1
#define __NR_setdomainname                      -1
#define __NR_uname                              68
#define __NR_modify_ldt                         -1
#define __NR_adjtimex                           -1
#define __NR_create_module                      -1
#define __NR_init_module                        -1
#define __NR_delete_module                      -1
#define __NR_get_kernel_syms                    -1
#define __NR_quotactl                           -1
#define __NR_fchdir                             71
#define __NR_bdflush                            -1
#define __NR_sysfs                              -1
#define __NR_personality                        -1
#define __NR_afs_syscall                        -1
#define __NR_setfsuid                           -1
#define __NR_setfsgid                           -1
#define __NR__llseek                            __NR_lseek
#define __NR__newselect                         __NR_select
#define __NR_flock                              101
#define __NR_msync                              -1
#define __NR_readv                              76
#define __NR_writev                             77
#define __NR_getsid                             67
#define __NR_fdatasync                          103
#define __NR__sysctl                            -1
#define __NR_mlock                              -1
#define __NR_munlock                            -1
#define __NR_mlockall                           -1
#define __NR_munlockall                         -1
#define __NR_sched_setparam                     -1
#define __NR_sched_getparam                     -1
#define __NR_sched_setscheduler                 -1
#define __NR_sched_getscheduler                 -1
#define __NR_sched_yield                        105
#define __NR_sched_get_priority_max             -1
#define __NR_sched_get_priority_min             -1
#define __NR_sched_rr_get_interval              -1
#define __NR_setresuid                          -1
#define __NR_getresuid                          -1
#define __NR_vm86                               -1
#define __NR_query_module                       -1
#define __NR_poll                               79
#define __NR_nfsservctl                         -1
#define __NR_setresgid                          -1
#define __NR_getresgid                          -1
#define __NR_prctl                              -1
#define __NR_rt_sigreturn                       80
#define __NR_rt_sigpending                      -1
#define __NR_rt_sigtimedwait                    -1
#define __NR_rt_sigqueueinfo                    -1
#define __NR_rt_sigsuspend                      -1
#define __NR_pread                              -1
#define __NR_pwrite                             -1
#define __NR_capget                             -1
#define __NR_capset                             -1
#define __NR_sigaltstack                        -1
#define __NR_sendfile                           -1
#define __NR_getpmsg                            -1
#define __NR_putpmsg                            -1
#define __NR_vfork                              __NR_fork
#define __NR_ugetrlimit                         __NR_getrlimit
#define __NR_mmap2                              __NR_mmap
#define __NR_truncate64                         -1
#define __NR_ftruncate64                        -1
#define __NR_stat64                             __NR_stat
#define __NR_lstat64                            __NR_lstat
#define __NR_fstat64                            __NR_fstat
#define __NR_lchown32                           -1
#define __NR_getuid32                           __NR_getuid
#define __NR_getgid32                           __NR_getgid
#define __NR_geteuid32                          __NR_geteuid
#define __NR_getegid32                          __NR_getegid
#define __NR_setreuid32                         -1
#define __NR_setregid32                         -1
#define __NR_getgroups32                        -1
#define __NR_setgroups32                        -1
#define __NR_fchown32                           -1
#define __NR_setresuid32                        -1
#define __NR_getresuid32                        -1
#define __NR_setresgid32                        -1
#define __NR_getresgid32                        -1
#define __NR_chown32                            __NR_chown
#define __NR_setuid32                           __NR_setuid
#define __NR_setgid32                           __NR_setgid
#define __NR_setfsuid32                         -1
#define __NR_setfsgid32                         -1
#define __NR_pivot_root                         -1
#define __NR_mincore                            -1
#define __NR_madvise                            -1
#define __NR_madvise1                           __NR_madvise
#define __NR_getdents64                         98
#define __NR_fcntl64                            __NR_fcntl
#define __NR_gettid                             106
#define __NR_readahead                          -1
#define __NR_setxattr                           -1
#define __NR_lsetxattr                          -1
#define __NR_fsetxattr                          -1
#define __NR_getxattr                           -1
#define __NR_lgetxattr                          -1
#define __NR_fgetxattr                          -1
#define __NR_listxattr                          -1
#define __NR_llistxattr                         -1
#define __NR_flistxattr                         -1
#define __NR_removexattr                        -1
#define __NR_lremovexattr                       -1
#define __NR_fremovexattr                       -1
#define __NR_tkill                              -1
#define __NR_sendfile64                         -1
#define __NR_futex                              -1
#define __NR_sched_setaffinity                  -1
#define __NR_sched_getaffinity                  -1
#define __NR_set_thread_area                    -1
#define __NR_get_thread_area                    -1
#define __NR_io_setup                           -1
#define __NR_io_destroy                         -1
#define __NR_io_getevents                       -1
#define __NR_io_submit                          -1
#define __NR_io_cancel                          -1
#define __NR_fadvise64                          -1
#define __NR_fadvise64_64                       -1
#define __NR_exit_group                         __NR_exit
#define __NR_lookup_dcookie                     -1
#define __NR_epoll_create                       -1
#define __NR_epoll_ctl                          -1
#define __NR_epoll_wait                         -1
#define __NR_remap_file_pages                   -1
#define __NR_set_tid_address                    112
#define __NR_timer_create                       -1
#define __NR_timer_settime                      -1
#define __NR_timer_gettime                      -1
#define __NR_timer_getoverrun                   -1
#define __NR_timer_delete                       -1
#define __NR_clock_settime                      -1
#define __NR_clock_getres                       -1
#define __NR_clock_nanosleep                    -1
#define __NR_statfs64                           -1
#define __NR_fstatfs64                          -1
#define __NR_tgkill                             -1
#define __NR_utimes                             -1
#define __NR_vserver                            -1
#define __NR_mbind                              -1
#define __NR_get_mempolicy                      -1
#define __NR_set_mempolicy                      -1
#define __NR_mq_open                            -1
#define __NR_mq_unlink                          -1
#define __NR_mq_timedsend                       -1
#define __NR_mq_timedreceive                    -1
#define __NR_mq_notify                          -1
#define __NR_mq_getsetattr                      -1
#define __NR_sys_kexec_load                     -1
#define __NR_waitid                             -1
#define __NR_add_key                            -1
#define __NR_request_key                        -1
#define __NR_keyctl                             -1
#define __NR_ioprio_set                         -1
#define __NR_ioprio_get                         -1
#define __NR_inotify_init                       -1
#define __NR_inotify_add_watch                  -1
#define __NR_inotify_rm_watch                   -1
#define __NR_migrate_pages                      -1
#define __NR_openat                             109
#define __NR_mkdirat                            110
#define __NR_mknodat                            -1
#define __NR_fchownat                           -1
#define __NR_futimesat                          -1
#define __NR_fstatat64                          -1
#define __NR_unlinkat                           111
#define __NR_renameat                           -1
#define __NR_linkat                             -1
#define __NR_symlinkat                          -1
#define __NR_readlinkat                         -1
#define __NR_fchmodat                           -1
#define __NR_faccessat                          -1
#define __NR_pselect6                           -1
#define __NR_ppoll                              __NR_poll
#define __NR_unshare                            -1
#define __NR_set_robust_list                    -1
#define __NR_get_robust_list                    -1
#define __NR_splice                             -1
#define __NR_sync_file_range                    -1
#define __NR_tee                                -1
#define __NR_vmsplice                           -1
#define __NR_move_pages                         -1
#define __NR_getcpu                             -1
#define __NR_epoll_pwait                        -1
#define __NR_utimensat                          -1
#define __NR_signalfd                           -1
#define __NR_timerfd                            -1
#define __NR_eventfd                            -1
#define __NR_fallocate                          -1
#define __NR_timerfd_settime                    -1
#define __NR_timerfd_gettime                    -1
#define __NR_signalfd4                          -1
#define __NR_eventfd2                           -1
#define __NR_epoll_create1                      -1
#define __NR_dup3                               99
#define __NR_pipe2                              104
#define __NR_inotify_init1                      -1
#define __NR_preadv                             -1
#define __NR_pwritev                            -1
#define __NR_rt_tgsigqueueinfo                  -1
#define __NR_perf_event_open                    -1
#define __NR_recvmmsg                           -1
#define __NR_fanotify_init                      -1
#define __NR_fanotify_mark                      -1
#define __NR_prlimit64                          -1
#define __NR_name_to_handle_at                  -1
#define __NR_open_by_handle_at                  -1
#define __NR_clock_adjtime                      -1
#define __NR_syncfs                             -1
#define __NR_sendmmsg                           -1
#define __NR_setns                              -1
#define __NR_process_vm_readv                   -1
#define __NR_process_vm_writev                  -1
#define __NR_kcmp                               -1
#define __NR_finit_module                       -1
#define __NR_sched_setattr                      -1
#define __NR_sched_getattr                      -1
#define __NR_renameat2                          -1
#define __NR_seccomp                            -1
#define __NR_getrandom                          -1
#define __NR_memfd_create                       -1
#define __NR_bpf                                -1
#define __NR_execveat                           -1
#define __NR_socket                             81
#define __NR_socketpair                         95
#define __NR_bind                               82
#define __NR_connect                            85
#define __NR_listen                             83
#define __NR_accept4                            84
#define __NR_getsockopt                         90
#define __NR_setsockopt                         89
#define __NR_getsockname                        91
#define __NR_getpeername                        92
#define __NR_sendto                             86
#define __NR_sendmsg                            93
#define __NR_recvfrom                           87
#define __NR_recvmsg                            94
#define __NR_shutdown                           88
#define __NR_userfaultfd                        -1
#define __NR_membarrier                         -1
#define __NR_mlock2                             -1
#define __NR_copy_file_range                    -1
#define __NR_preadv2                            -1
#define __NR_pwritev2                           -1
#define __NR_pkey_mprotect                      -1
#define __NR_pkey_alloc                         -1
#define __NR_pkey_free                          -1
#define __NR_ia32_statx                         -1
#define __NR_ia32_arch_prctl                    -1
#define __NR_ia32_io_pgetevents                 -1
#define __NR_ia32_rseq                          -1

#define syscall_weak(name,wsym,sym) \
.text; \
.type wsym,@function; \
.weak wsym; \
wsym: ; \
.type sym,@function; \
.global sym; \
sym: \
.ifle __NR_##name-255; \
	movb $__NR_##name,%al; \
	jmp __unified_syscall; \
.else; \
	movw $__NR_##name,%ax; \
	jmp __unified_syscall_256; \
.endif; \
.Lend##sym: ; \
.size sym,.Lend##sym-sym

#define syscall(name,sym) \
.text; \
.type sym,@function; \
.global sym; \
sym: \
.ifle __NR_##name-255; \
	movb $__NR_##name,%al; \
	jmp __unified_syscall; \
.else; \
	movw $__NR_##name,%ax; \
	jmp __unified_syscall_256; \
.endif; \
.Lend##sym: ; \
.size sym,.Lend##sym-sym

#ifndef __DYN_LIB
#define __socketcall(name,NAME) \
.text; \
.type name,@function; \
.weak name; \
name: ; \
.type __libc_##name,@function; \
.global __libc_##name; \
__libc_##name: ; \
	movb $SYS_##NAME,%al; \
	jmp socketcall; \
.Lend##name:; \
.size name,.Lend##name-name
#else
#define __socketcall(name,NAME)
#endif
