/*<<< WORK-IN-PROGRESS MODERNIZATION HEADER
  This repository is a work in progress to reproduce the
  original MINIX simplicity on modern 32-bit and 64-bit
  ARM and x86/x86_64 hardware using C++17.
>>>*/

#include "../include/ctype.hpp" // classification helpers

/* Table used by the inline classification functions in ctype.hpp. */
char ctype_[] = {0,
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(S),
                  static_cast<char>(S),
                  static_cast<char>(S),
                  static_cast<char>(S),
                  static_cast<char>(S),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(C),
                  static_cast<char>(S),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(N),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(U | X),
                  static_cast<char>(U | X),
                  static_cast<char>(U | X),
                  static_cast<char>(U | X),
                  static_cast<char>(U | X),
                  static_cast<char>(U | X),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(U),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(L | X),
                  static_cast<char>(L | X),
                  static_cast<char>(L | X),
                  static_cast<char>(L | X),
                  static_cast<char>(L | X),
                  static_cast<char>(L | X),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(L),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(P),
                  static_cast<char>(C)};
