#include "../include/ctype.hpp" // classification helpers

/* Table used by the inline classification functions in ctype.hpp. */
char _ctype_[] = {0,
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_S),
                  static_cast<char>(_S),
                  static_cast<char>(_S),
                  static_cast<char>(_S),
                  static_cast<char>(_S),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_C),
                  static_cast<char>(_S),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_N),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U | _X),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_U),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L | _X),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_L),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_P),
                  static_cast<char>(_C)};
