#include "../include/ctype.hpp" // classification helpers

/**
 * @file ctype.cpp
 * @brief Defines and initializes the global character classification table.
 *
 * This file contains the storage for the `ctype_` character classification table.
 * The corresponding header file, `ctype.hpp`, declares this table as `extern`,
 * and defines a set of `inline` functions that use it. By undefining the `EXTERN`
 * macro here before including the headers, we ensure that the global `ctype_`
 * array is allocated exactly once during the build process, preventing linker errors.
 *
 * This separation of declaration from definition is a classic C/C++ pattern
 * and is a critical part of the library's architecture. The table itself is a
 * lookup mechanism that stores bitmasks for each character, allowing for
 * highly efficient character classification.
 *
 * @ingroup utility
 */
char ctype_[] = {0,
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(S),
                 static_cast<char>(S),
                 static_cast<char>(S),
                 static_cast<char>(S),
                 static_cast<char>(S),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(C),
                 static_cast<char>(S),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(N),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(U | X),
                 static_cast<char>(U | X),
                 static_cast<char>(U | X),
                 static_cast<char>(U | X),
                 static_cast<char>(U | X),
                 static_cast<char>(U | X),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(U),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(L | X),
                 static_cast<char>(L | X),
                 static_cast<char>(L | X),
                 static_cast<char>(L | X),
                 static_cast<char>(L | X),
                 static_cast<char>(L | X),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(L),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(P),
                 static_cast<char>(C)};