/**
 * @file indcpa.cpp
 * @brief Kyber IND-CPA public-key encryption scheme.
 *
 * Implements key generation, encryption, and decryption for the
 * Kyber IND-CPA PKE.  Based on CRYSTALS-Kyber round 3 reference.
 *
 * gen_matrix:             expand matrix A from a 32-byte seed using SHAKE128
 * indcpa_keypair_derand:  generate (pk, sk) deterministically from 32 coins
 * indcpa_enc:             encrypt message m under pk with randomness coins
 * indcpa_dec:             decrypt ciphertext c under sk -> m
 */

#include "indcpa.h"
#include "polyvec.h"
#include "poly.h"
#include "ntt.h"
#include "symmetric.h"
#include "randombytes.hpp"
#include <stdint.h>
#include <cstring>

/*
 * Pack a polyvec public key and rho seed into pk bytes.
 * Layout: polyvec_tobytes(pk) || rho (32 bytes)
 */
static void pack_pk(uint8_t pk[KYBER_INDCPA_PUBLICKEYBYTES],
                    const polyvec *pk_pv,
                    const uint8_t rho[KYBER_SYMBYTES]) {
    polyvec_tobytes(pk, pk_pv);
    std::memcpy(pk + KYBER_POLYVECBYTES, rho, KYBER_SYMBYTES);
}

static void unpack_pk(polyvec *pk_pv,
                      uint8_t rho[KYBER_SYMBYTES],
                      const uint8_t pk[KYBER_INDCPA_PUBLICKEYBYTES]) {
    polyvec_frombytes(pk_pv, pk);
    std::memcpy(rho, pk + KYBER_POLYVECBYTES, KYBER_SYMBYTES);
}

static void pack_sk(uint8_t sk[KYBER_INDCPA_SECRETKEYBYTES],
                    const polyvec *sk_pv) {
    polyvec_tobytes(sk, sk_pv);
}

static void unpack_sk(polyvec *sk_pv,
                      const uint8_t sk[KYBER_INDCPA_SECRETKEYBYTES]) {
    polyvec_frombytes(sk_pv, sk);
}

static void pack_ciphertext(uint8_t c[KYBER_INDCPA_BYTES],
                            const polyvec *b_pv,
                            const poly *v) {
    polyvec_compress(c, b_pv);
    poly_compress(c + KYBER_POLYVECCOMPRESSEDBYTES, v);
}

static void unpack_ciphertext(polyvec *b_pv,
                              poly *v,
                              const uint8_t c[KYBER_INDCPA_BYTES]) {
    polyvec_decompress(b_pv, c);
    poly_decompress(v, c + KYBER_POLYVECCOMPRESSEDBYTES);
}

/*
 * Rejection sampling: draw NTT coefficients in [0, q) from a SHAKE128 stream.
 * Returns the number of coefficients written (may be less than len on a block).
 */
static unsigned int rej_uniform(int16_t *r,
                                 unsigned int len,
                                 const uint8_t *buf,
                                 unsigned int buflen) {
    unsigned int ctr = 0;
    unsigned int pos = 0;
    while (ctr < len && pos + 3 <= buflen) {
        uint16_t val0 = ((buf[pos + 0] >> 0) | ((uint16_t)buf[pos + 1] << 8)) & 0xFFF;
        uint16_t val1 = ((buf[pos + 1] >> 4) | ((uint16_t)buf[pos + 2] << 4)) & 0xFFF;
        pos += 3;
        if (val0 < KYBER_Q)
            r[ctr++] = static_cast<int16_t>(val0);
        if (ctr < len && val1 < KYBER_Q)
            r[ctr++] = static_cast<int16_t>(val1);
    }
    return ctr;
}

#define GEN_MATRIX_NBLOCKS \
    ((12 * KYBER_N / 8 * (1 << 12) / KYBER_Q + XOF_BLOCKBYTES) / XOF_BLOCKBYTES)

/*
 * gen_matrix: generate matrix A (or A^T when transposed != 0).
 * Each entry A[i][j] is a polynomial in NTT domain generated by
 * SHAKE128(rho || j || i).  (Transposed: SHAKE128(rho || i || j).)
 */
void gen_matrix(polyvec *a, const uint8_t seed[KYBER_SYMBYTES], int transposed) {
    uint8_t buf[GEN_MATRIX_NBLOCKS * XOF_BLOCKBYTES + 2];
    xof_state state;

    for (unsigned int i = 0; i < KYBER_K; i++) {
        for (unsigned int j = 0; j < KYBER_K; j++) {
            if (transposed) {
                xof_absorb(&state, seed, (uint8_t)i, (uint8_t)j);
            } else {
                xof_absorb(&state, seed, (uint8_t)j, (uint8_t)i);
            }

            xof_squeezeblocks(buf, GEN_MATRIX_NBLOCKS, &state);
            unsigned int buflen = GEN_MATRIX_NBLOCKS * XOF_BLOCKBYTES;

            unsigned int ctr = rej_uniform(a[i].vec[j].coeffs, KYBER_N, buf, buflen);

            while (ctr < KYBER_N) {
                unsigned int off = buflen % 3;
                // Shift leftover bytes to front, squeeze one more block
                for (unsigned int k = 0; k < off; k++)
                    buf[k] = buf[buflen - off + k];
                xof_squeezeblocks(buf + off, 1, &state);
                buflen = off + XOF_BLOCKBYTES;
                ctr += rej_uniform(a[i].vec[j].coeffs + ctr,
                                   KYBER_N - ctr, buf, buflen);
            }
        }
    }
}

void indcpa_keypair_derand(uint8_t pk[KYBER_INDCPA_PUBLICKEYBYTES],
                           uint8_t sk[KYBER_INDCPA_SECRETKEYBYTES],
                           const uint8_t coins[KYBER_SYMBYTES]) {
    uint8_t buf[2 * KYBER_SYMBYTES];
    std::memcpy(buf, coins, KYBER_SYMBYTES);
    buf[KYBER_SYMBYTES] = KYBER_K;
    hash_g(buf, buf, KYBER_SYMBYTES + 1);

    const uint8_t *rho = buf;
    const uint8_t *sigma = buf + KYBER_SYMBYTES;

    polyvec a[KYBER_K], e, pkpv, skpv;
    gen_matrix(a, rho, 0);

    uint8_t nonce = 0;
    for (unsigned int i = 0; i < KYBER_K; i++) {
        poly_getnoise_eta1(&skpv.vec[i], sigma, nonce++);
    }
    for (unsigned int i = 0; i < KYBER_K; i++) {
        poly_getnoise_eta1(&e.vec[i], sigma, nonce++);
    }

    polyvec_ntt(&skpv);
    polyvec_ntt(&e);

    // pkpv = A * skpv + e (all in NTT domain)
    for (unsigned int i = 0; i < KYBER_K; i++) {
        polyvec_basemul_acc_montgomery(&pkpv.vec[i], &a[i], &skpv);
        poly_tomont(&pkpv.vec[i]);
    }

    polyvec_add(&pkpv, &pkpv, &e);
    polyvec_reduce(&pkpv);

    pack_sk(sk, &skpv);
    pack_pk(pk, &pkpv, rho);
}

void indcpa_enc(uint8_t c[KYBER_INDCPA_BYTES],
                const uint8_t m[KYBER_INDCPA_MSGBYTES],
                const uint8_t pk[KYBER_INDCPA_PUBLICKEYBYTES],
                const uint8_t coins[KYBER_SYMBYTES]) {
    uint8_t seed[KYBER_SYMBYTES];
    polyvec sp, pkpv, ep, at[KYBER_K], b;
    poly v, k, epp;

    unpack_pk(&pkpv, seed, pk);

    poly_frommsg(&k, m);
    gen_matrix(at, seed, 1); // transposed A

    uint8_t nonce = 0;
    for (unsigned int i = 0; i < KYBER_K; i++) {
        poly_getnoise_eta1(&sp.vec[i], coins, nonce++);
    }
    for (unsigned int i = 0; i < KYBER_K; i++) {
        poly_getnoise_eta2(&ep.vec[i], coins, nonce++);
    }
    poly_getnoise_eta2(&epp, coins, nonce);

    polyvec_ntt(&sp);

    // b = A^T * sp (NTT domain, basemul output is R^{-1}-scaled)
    for (unsigned int i = 0; i < KYBER_K; i++) {
        polyvec_basemul_acc_montgomery(&b.vec[i], &at[i], &sp);
    }

    // v = pkpv^T * sp (NTT domain, basemul output is R^{-1}-scaled)
    polyvec_basemul_acc_montgomery(&v, &pkpv, &sp);

    // Convert to time domain: invntt_tomont scales by R, cancelling R^{-1}
    polyvec_invntt_tomont(&b);
    poly_invntt_tomont(&v);

    // Add noise and message in time domain (all standard-domain now)
    polyvec_add(&b, &b, &ep);
    poly_add(&v, &v, &epp);
    poly_add(&v, &v, &k);
    polyvec_reduce(&b);
    poly_reduce(&v);

    pack_ciphertext(c, &b, &v);
}

void indcpa_dec(uint8_t m[KYBER_INDCPA_MSGBYTES],
                const uint8_t c[KYBER_INDCPA_BYTES],
                const uint8_t sk[KYBER_INDCPA_SECRETKEYBYTES]) {
    polyvec b, skpv;
    poly v, mp;

    unpack_ciphertext(&b, &v, c);
    unpack_sk(&skpv, sk);

    polyvec_ntt(&b);

    // mp = skpv^T * b (basemul output is R^{-1}-scaled)
    polyvec_basemul_acc_montgomery(&mp, &skpv, &b);
    poly_invntt_tomont(&mp);

    poly_sub(&mp, &v, &mp);
    poly_reduce(&mp);

    poly_tomsg(m, &mp);
}
