#pragma once

/* Native XINIM syscall numbers shared by C, C++, and assembly entry code. */

#define XINIM_NATIVE_SYS_EXIT 25
#define XINIM_NATIVE_SYS_OPEN 3
#define XINIM_NATIVE_SYS_CLOSE 4
#define XINIM_NATIVE_SYS_READ 5
#define XINIM_NATIVE_SYS_STAT 8
#define XINIM_NATIVE_SYS_FSTAT 9
#define XINIM_NATIVE_SYS_FCNTL 15
#define XINIM_NATIVE_SYS_DUP 11
#define XINIM_NATIVE_SYS_PIPE 13
#define XINIM_NATIVE_SYS_FORK 26
#define XINIM_NATIVE_SYS_EXECVE 27
#define XINIM_NATIVE_SYS_WAIT4 28
#define XINIM_NATIVE_SYS_WRITE 6
#define XINIM_NATIVE_SYS_IOCTL 14
#define XINIM_NATIVE_SYS_BRK 34
#define XINIM_NATIVE_SYS_MMAP 35
#define XINIM_NATIVE_SYS_MUNMAP 36
#define XINIM_NATIVE_SYS_TIME 42
#define XINIM_NATIVE_SYS_GETTIMEOFDAY 43
#define XINIM_NATIVE_SYS_CLOCK_GETTIME 44
#define XINIM_NATIVE_SYS_NANOSLEEP 45
#define XINIM_NATIVE_SYS_ALARM 52
#define XINIM_NATIVE_SYS_GETRLIMIT 53
#define XINIM_NATIVE_SYS_GETRUSAGE 55
#define XINIM_NATIVE_SYS_UMASK 57
#define XINIM_NATIVE_SYS_GETPID 29
#define XINIM_NATIVE_SYS_KILL 31
#define XINIM_NATIVE_SYS_SIGACTION 33
#define XINIM_NATIVE_SYS_RT_SIGPROCMASK 61
#define XINIM_NATIVE_SYS_GETPGID 62
#define XINIM_NATIVE_SYS_GETDENTS 63
#define XINIM_NATIVE_SYS_MREMAP 64
#define XINIM_NATIVE_SYS_SELECT 78
#define XINIM_NATIVE_SYS_SIGSUSPEND 97
#define XINIM_NATIVE_SYS_SETPGID 65
#define XINIM_NATIVE_SYS_SYMLINK 69
#define XINIM_NATIVE_SYS_READLINK 70
#define XINIM_NATIVE_SYS_LSTAT 108
#define XINIM_NATIVE_SYS_CHOWN 24
#define XINIM_NATIVE_SYS_FCHOWN 73
#define XINIM_NATIVE_SYS_TRUNCATE 74
#define XINIM_NATIVE_SYS_FTRUNCATE 75
#define XINIM_NATIVE_SYS_FLOCK 101
