#pragma once
// TTY line discipline for the i486 kernel.
// Cleanroom implementation per POSIX.1 (IEEE Std 1003.1) termios specification.

#include <stdint.h>

namespace xinim::i486::tty {

// termios c_lflag bits (POSIX.1)
constexpr uint32_t kIsig   = 0001U;
constexpr uint32_t kIcanon = 0002U;
constexpr uint32_t kEcho   = 0010U;
constexpr uint32_t kEchoe  = 0020U;
constexpr uint32_t kEchok  = 0040U;
constexpr uint32_t kEchonl = 0100U;
constexpr uint32_t kNoflsh = 0200U;
constexpr uint32_t kIexten = 0100000U;

// termios c_iflag bits
constexpr uint32_t kInlcr  = 0000100U;
constexpr uint32_t kIgncr  = 0000200U;
constexpr uint32_t kIcrnl  = 0000400U;
constexpr uint32_t kIxon   = 0002000U;
constexpr uint32_t kIxoff  = 0010000U;

// termios c_oflag bits
constexpr uint32_t kOpost  = 0000001U;
constexpr uint32_t kOnlcr  = 0000004U;

// c_cc indices (POSIX.1 / Linux ABI)
constexpr int kVintr  = 0;  // Ctrl+C
constexpr int kVquit  = 1;  // Ctrl+backslash
constexpr int kVerase = 2;  // Backspace/DEL
constexpr int kVkill  = 3;  // Ctrl+U
constexpr int kVeof   = 4;  // Ctrl+D
constexpr int kVtime  = 5;
constexpr int kVmin   = 6;
constexpr int kVstart = 8;  // Ctrl+Q (XON)
constexpr int kVstop  = 9;  // Ctrl+S (XOFF)
constexpr int kVsusp  = 10; // Ctrl+Z
constexpr int kVwerase = 11; // Ctrl+W (word erase, POSIX.1 c_cc extension)
constexpr int kVreprint = 12; // Ctrl+R (reprint line, POSIX.1 c_cc extension)
constexpr int kVlnext = 14; // Ctrl+V (literal next, POSIX.1 c_cc extension)

struct TermiosState {
    uint32_t c_iflag;
    uint32_t c_oflag;
    uint32_t c_cflag;
    uint32_t c_lflag;
    uint8_t c_line;
    uint8_t c_cc[19];
};

struct WindowSize {
    uint16_t ws_row;
    uint16_t ws_col;
    uint16_t ws_xpixel;
    uint16_t ws_ypixel;
};

// Initialize the TTY subsystem with default termios.
void initialize() noexcept;

// Process a raw character from keyboard/serial through the line discipline.
// In canonical mode, buffers until newline/EOF. In raw mode, makes it
// immediately available.
void input_char(char c) noexcept;

// Read processed characters from the line discipline output buffer.
// Returns number of bytes read, 0 for EOF, or -1 if no data available (would block).
int read(void* buffer, uint32_t count) noexcept;

// Check if there is data available for reading.
bool has_input() noexcept;

// Get/set termios state.
void get_termios(TermiosState* out) noexcept;
void set_termios(const TermiosState* state) noexcept;

// Get/set window size.
void get_winsize(WindowSize* out) noexcept;
void set_winsize(const WindowSize* ws) noexcept;

// Check if canonical mode line is complete (has newline or EOF).
bool canonical_line_ready() noexcept;

// Consume any pending signal generated by the line discipline (ISIG).
// Returns signal number (e.g. 2=SIGINT, 3=SIGQUIT, 20=SIGTSTP) or 0 if none.
uint32_t consume_pending_ldisc_signal() noexcept;

} // namespace xinim::i486::tty
