name: CMake Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build -- -j$(nproc)
    - name: Run sample tests
      run: |
        for t in $(sed '/^echo/d' test/run); do
          make -C test f=$t
          ./test/$t
        done
