name: pre-commit

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy cppcheck cloc cscope python3-pip
          pip install pre-commit lizard
      - name: Run pre-commit
        run: pre-commit run --all-files
